// <auto-generated />
using Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.Migrations
{
    [DbContext(typeof(TernakLeleHmsContext))]
    partial class TernakLeleHmsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Api.Models.Inventory", b =>
                {
                    b.Property<long>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CrossReference");

                    b.Property<string>("Description");

                    b.Property<int>("DistributionUnit");

                    b.Property<int>("InventoryType");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<double>("Quantity");

                    b.Property<int>("Rank");

                    b.Property<double>("ReorderPoint");

                    b.HasKey("InventoryId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new { InventoryId = 1L, CrossReference = "Test", Description = "fwefwe", DistributionUnit = 0, InventoryType = 0, Name = "cdscsdc", Price = 5.25m, Quantity = 2.0, Rank = 1, ReorderPoint = 3.0 },
                        new { InventoryId = 2L, CrossReference = "vdfvd", Description = "bdbd", DistributionUnit = 1, InventoryType = 1, Name = "vdfvf", Price = 7.34m, Quantity = 6.0, Rank = 2, ReorderPoint = 11.0 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
