using System;
using Common.Enums;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Api.Models
{
    public class Inventory
    {
        public Inventory() {}

        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        public long InventoryId { get; set; }
        public string CrossReference { get; set; }
        public string Description { get; set; }
        public DistributionUnit DistributionUnit { get; set; }
        public InventoryType InventoryType { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public double Quantity { get; set; }
        public Rank Rank { get; set; }
        public double ReorderPoint { get; set; }

        [BsonDateTimeOptions]
        // attribute to gain control on datetime serialization
        public DateTime UpdatedOn { get; set; } = DateTime.Now;
    }
}
